general {
    lock_cmd = pidof swaylock || swaylock     # launch one swaylock instance
    unlock_cmd = notify-send "Unlocking..."      # same as above, but unlock
    before_sleep_cmd = loginctl lock-session    # lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on  # turn screens back on after wake
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

listener {
    timeout = 300 # 5 minutes - lock the screen
    on-timeout = loginctl lock-session
    on-resume =
}

listener {
    timeout = 500 # ~8 minutes - turn off the screen
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

