providers:
  - yay
  - bun
modules:
  - desktop
  - core
  - audio-media
  - applications
  - endeavouros
  - development
  - file-management
  - fonts
  - hardware
  - network
  - system-core
  - system-utilities
variables:
  HOMEDIR: "/home/firesquid"
